services:
  srmain:
    image: anup84/srmain:latest
    #command: pnpm run start:dev srmain
    env_file:
      - ./apps/srmain/.env
    ports:
      - '3000:3000'
    volumes:
      - ./apps/srmain/src:/usr/src/app/apps/srmain/src

  auth:
    image: anup84/auth:latest
    #command: pnpm run start:dev auth
    env_file:
      - ./apps/auth/.env
    ports:
      - '3001:3001'
    volumes:
      - ./apps/auth/src:/usr/src/app/apps/auth/src

  payments:
    image: anup84/payments:latest
    #command: pnpm run start:dev payments
    env_file:
      - ./apps/payments/.env
    volumes:
      - ./apps/payments/src:/usr/src/app/apps/payments/src

  notifications:
    image: anup84/notifications:latest
    #command: pnpm run start:dev notifications
    env_file:
      - ./apps/notifications/.env
    volumes:
      - ./apps/notifications/src:/usr/src/app/apps/notifications/src

  #mongo:
  # image: mongo
