services:
  srmain:
    build:
      context: .
      dockerfile: ./apps/srmain/Dockerfile
      target: production
    command: pnpm run start:dev srmain
    env_file:
      - ./apps/srmain/.env
    ports:
      - '3000:3000'
    volumes:
      - ./apps/srmain/src:/usr/src/app/apps/srmain/src

  auth:
    build:
      context: .
      dockerfile: ./apps/auth/Dockerfile
      target: production
    command: pnpm run start:dev auth
    env_file:
      - ./apps/auth/.env
    ports:
      - '3001:3001'
    volumes:
      - ./apps/auth/src:/usr/src/app/apps/auth/src

  payments:
    build:
      context: .
      dockerfile: ./apps/payments/Dockerfile
      target: production
    command: pnpm run start:dev payments
    env_file:
      - ./apps/payments/.env
    volumes:
      - ./apps/payments/src:/usr/src/app/apps/payments/src

  notifications:
    build:
      context: .
      dockerfile: ./apps/notifications/Dockerfile
      target: production
    command: pnpm run start:dev notifications
    env_file:
      - ./apps/notifications/.env
    volumes:
      - ./apps/notifications/src:/usr/src/app/apps/notifications/src

  #mongo:
  # image: mongo
