receivers:
  hostmetrics:
    collection_interval: 10s
    scrapers:
      cpu:
      memory:
      disk:
      filesystem:
      network:

processors:
  batch:
    timeout: 10s

exporters:
  otlphttp:
    endpoint: 'http://localhost/api/metrics' # Replace with your actual endpoint
    headers:
      Authorization: 'Bearer YOUR_JWT_TOKEN' # Replace with the actual JWT token
      Content-Type: 'application/x-otlp+json'
    compression: 'gzip' # Optional: enables gzip compression
    timeout: 10s

service:
  pipelines:
    metrics:
      receivers: [hostmetrics]
      processors: [batch]
      exporters: [otlphttp]
