#this is for production build test, this is kind of simpley running helm install siterel "k8s/siterel".
#the images are already being built and pushed on docker hub based on github work flow.
#do skaffold run -f skaffold-prod.yaml --tail
apiVersion: skaffold/v4beta11
kind: Config
deploy:
  helm:
    releases:
      - name: siterel
        chartPath: ./k8s/siterel
        valuesFiles:
          - ./k8s/siterel/values-prod.yaml
        setValues:
          global.environment: prod
