apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: auth
  name: auth
spec:
  replicas: 1
  selector:
    matchLabels:
      app: auth
  template:
    metadata:
      labels:
        app: auth
    spec:
      containers:
        - image: {{ .Values.auth.image }}
          name: auth
          command: {{ .Values.auth.command | toJson }}
          env:
            - name: MONGODB_URI
              valueFrom:
                secretKeyRef:
                  name: mongodb
                  key: connectionString

            - name: JWT_SECRET
              valueFrom:
                secretKeyRef:
                  name: jwt
                  key: jwtSecret

            - name: JWT_EXPIRATION
              value: '3600'

            - name: HTTP_PORT
              value: '3001'

            - name: AUTH_GRPC_URL
              value: 'auth-tcp:5001'

          ports:
            - containerPort: 3001
            - containerPort: 3002
