apiVersion: v1
kind: Service
metadata:
  labels:
    app: auth
  name: auth-tcp
spec:
  ports:
    - name: 'tcp'
      port: 5001
      protocol: TCP
      targetPort: 5001
  selector:
    app: auth
  type: ClusterIP
