apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: metrics
  name: metrics
spec:
  replicas: 1
  selector:
    matchLabels:
      app: metrics
  template:
    metadata:
      labels:
        app: metrics
    spec:
      containers:
        - image: {{ .Values.metrics.image }}
          name: metrics
          command: {{ .Values.metrics.command | toJson }}
          env:
            - name: MONGODB_URI
              valueFrom:
                secretKeyRef:
                  name: mongodb
                  key: connectionString

            - name: HTTP_PORT
              value: '3005'

            - name: AUTH_GRPC_URL
              value: 'auth-tcp:5001'
          ports:
            - containerPort: 3005
