apiVersion: v1
kind: Service
metadata:
  labels:
    app: metrics
  name: metrics
spec:
  ports:
    - name: 'http'
      port: 3005
      protocol: TCP
      targetPort: 3005
  selector:
    app: metrics
  type: ClusterIP
