#values for dev environement
global:
  environment: dev
auth:
  image: anup84/auth:latest
  command: ['pnpm', 'run', 'start:dev', 'auth']
central:
  image: anup84/central:latest
  command: ['pnpm', 'run', 'start:dev', 'central']
payments:
  image: anup84/payments:latest
  command: ['pnpm', 'run', 'start:dev', 'payments']
notifications:
  image: anup84/notifications:latest
  command: ['pnpm', 'run', 'start:dev', 'notifications']
