#values for production environment
global:
  environment: dev
auth:
  image: anup84/auth:latest
  command: ['node', 'dist/apps/auth/main']
srmain:
  image: anup84/srmain:latest
  command: ['node', 'dist/apps/srmain/main']
payments:
  image: anup84/payments:latest
  command: ['node', 'dist/apps/payments/main']
notifications:
  image: anup84/notifications:latest
  command: ['node', 'dist/apps/notifications/main']
