// Code generated by protoc-gen-ts_proto. DO NOT EDIT.
// versions:
//   protoc-gen-ts_proto  v2.2.0
//   protoc               v3.12.4
// source: proto/auth.proto

/* eslint-disable */
import { GrpcMethod, GrpcStreamMethod } from "@nestjs/microservices";
import { Observable } from "rxjs";

export const protobufPackage = "auth";

export interface AuthenticationMessage {
  Authentication: string;
}

export interface UserMessage {
  userId: string;
  email: string;
  uType: string;
  accountId: string;
  roleId: string;
}

export interface CheckPermissionsRequest {
  roleId: string;
  subject: string;
  actions: string[];
}

export interface CheckPermissionsResponse {
  hasPermission: boolean;
}

export const AUTH_PACKAGE_NAME = "auth";

export interface AuthServiceClient {
  authenticate(request: AuthenticationMessage): Observable<UserMessage>;

  checkPermissions(request: CheckPermissionsRequest): Observable<CheckPermissionsResponse>;
}

export interface AuthServiceController {
  authenticate(request: AuthenticationMessage): Promise<UserMessage> | Observable<UserMessage> | UserMessage;

  checkPermissions(
    request: CheckPermissionsRequest,
  ): Promise<CheckPermissionsResponse> | Observable<CheckPermissionsResponse> | CheckPermissionsResponse;
}

export function AuthServiceControllerMethods() {
  return function (constructor: Function) {
    const grpcMethods: string[] = ["authenticate", "checkPermissions"];
    for (const method of grpcMethods) {
      const descriptor: any = Reflect.getOwnPropertyDescriptor(constructor.prototype, method);
      GrpcMethod("AuthService", method)(constructor.prototype[method], method, descriptor);
    }
    const grpcStreamMethods: string[] = [];
    for (const method of grpcStreamMethods) {
      const descriptor: any = Reflect.getOwnPropertyDescriptor(constructor.prototype, method);
      GrpcStreamMethod("AuthService", method)(constructor.prototype[method], method, descriptor);
    }
  };
}

export const AUTH_SERVICE_NAME = "AuthService";
