apiVersion: v1
kind: Service
metadata:
  labels:
    app: notifications
  name: notifications
spec:
  ports:
    - name: 'tcp'
      port: 5001
      protocol: TCP
      targetPort: 5001
  selector:
    app: notifications
  type: ClusterIP
