apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: srmain
  name: srmain
spec:
  replicas: 1
  selector:
    matchLabels:
      app: srmain
  template:
    metadata:
      labels:
        app: srmain
    spec:
      containers:
        - image: { { .Values.srmain.image } }
          name: srmain
          command: { { .Values.srmain.command | toJson } }
          env:
            - name: MONGODB_URI
              valueFrom:
                secretKeyRef:
                  name: mongodb
                  key: connectionString

            - name: HTTP_PORT
              value: '3000'
            - name: AUTH_GRPC_URL
              value: 'auth-tcp:5001'
            - name: PAYMENTS_GRPC_URL
              value: 'payments:5001'
          ports:
            - containerPort: 3000
