apiVersion: v1
kind: Service
metadata:
  labels:
    app: central
  name: central
spec:
  ports:
    - name: 'http'
      port: 3000
      protocol: TCP
      targetPort: 3000
  selector:
    app: central
  type: NodePort
