name: Docker Image CI

on:
  push:
    branches: ['main-random_branch_so_that_it_does_not_run_for_now']
  pull_request:
    branches: ['main-random_branch_so_that_it_does_not_run_for_now']

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Copy .env.sample to .env
        run: |
          cp ./apps/srmain/.env.sample ./apps/srmain/.env
          cp ./apps/auth/.env.sample ./apps/auth/.env
          cp ./apps/payments/.env.sample ./apps/payments/.env
          cp ./apps/notifications/.env.sample ./apps/notifications/.env

      - name: Log in to Docker Hub
        run: echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u ${{ secrets.DOCKER_USERNAME }} --password-stdin

      # Build and push service1 image
      - name: Build and push service1
        run: |
          docker compose build srmain
          docker tag sleepr-srmain:latest ${{ secrets.DOCKER_USERNAME }}/srmain:latest
          docker push ${{ secrets.DOCKER_USERNAME }}/srmain:latest
      - name: Build and push service2
        run: |
          docker compose build payments
          docker tag sleepr-payments:latest ${{ secrets.DOCKER_USERNAME }}/payments:latest
          docker push ${{ secrets.DOCKER_USERNAME }}/payments:latest
      - name: Build and push service3
        run: |
          docker compose build auth
          docker tag sleepr-auth:latest ${{ secrets.DOCKER_USERNAME }}/auth:latest
          docker push ${{ secrets.DOCKER_USERNAME }}/auth:latest
      - name: Build and push service4
        run: |
          docker compose build notifications
          docker tag sleepr-notifications:latest ${{ secrets.DOCKER_USERNAME }}/notifications:latest
          docker push ${{ secrets.DOCKER_USERNAME }}/notifications:latest
